#! /bin/sh
tr '[:upper:]' '[:lower:]' | sed "s/\`/\'/g" | awk "/^\s*<td>[pk'mnwlha eiou]*<\/td>\s*$/ {print;}" | sed 's/<[^>]*>//g' | sed 's/^\s*//g' | sed 's/\s*$//g' | tr ' ' '\n' | sed '/^$/d' | sort -u
